import PDFDocument from 'pdfkit';
import pool from '../config/database.js';
// 1. Import the official Google Gen AI SDK
import { GoogleGenAI } from '@google/genai';

// 2. Initialize the client (it automatically picks up process.env.GEMINI_API_KEY)
const ai = new GoogleGenAI({});

export const createQuestionnaire = async (userId, mcqAnswers, projectOverview) => {
    const query = `
        INSERT INTO questionnaires (user_id, mcq_answers, project_overview)
        VALUES ($1, $2, $3) RETURNING *;
    `;
    const values = [userId, JSON.stringify(mcqAnswers), projectOverview];
    const { rows } = await pool.query(query, values);
    return rows[0];
};


const callLLM = async (mcqAnswers, overview) => {
    try {
        
        const prompt = `
            You are an expert Project Manager. Generate a professional Project Scope Document based on the client's inputs.
            
            Client Project Overview:
            "${overview}"
            
            Client Requirements & Questionnaire Responses (MCQ):
            ${JSON.stringify(mcqAnswers, null, 2)}
            
            Please output a well-structured document containing:
            1. Executive Summary
            2. Core Project Deliverables
            3. Technical Stack & Architecture Guidelines (based on their choices)
            4. Estimated Timeline & Key Milestones
            
            Keep the tone formal, professional, and clear. Do not use Markdown formatting like bold asterisks (**) or hashes (#) because this text will be fed directly into a clean PDF generation tool.
        `;

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
        });

        // Return the clean text generated by the AI
        return response.text;
    } catch (error) {
    console.error("========== GEMINI ERROR ==========");
    console.error(error);

    if (error.response) {
        console.error("Response:", error.response);
    }

    console.error("Message:", error.message);
    console.error("Stack:", error.stack);

    throw error;
}
};

const generatePdfBuffer = (scopeText) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument();

    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));

    doc.on("end", () => {
      resolve(Buffer.concat(chunks));
    });

    doc.on("error", reject);

    doc.fontSize(20).text("PROJECT SCOPE DOCUMENT", {
      align: "center",
    });

    doc.moveDown(2);

    doc.fontSize(12).text(scopeText, {
      lineGap: 5,
    });

    doc.end();
  });
};

export const processScopeGeneration = async (userId, questionnaireId) => {

    const qCheck = await pool.query(
        "SELECT * FROM questionnaires WHERE id = $1 AND user_id = $2",
        [userId ? questionnaireId : questionnaireId, userId]
    );

    if (qCheck.rows.length === 0) {
        throw new Error("Questionnaire not found or access denied.");
    }

    const questionnaire = qCheck.rows[0];

    const generatedText = await callLLM(
        questionnaire.mcq_answers,
        questionnaire.project_overview
    );

    const insertScopeQuery = `
        INSERT INTO scopes
        (
            user_id,
            questionnaire_id,
            scope_text
        )
        VALUES
        ($1,$2,$3)
        RETURNING *;
    `;

    const { rows } = await pool.query(
        insertScopeQuery,
        [
            userId,
            questionnaireId,
            generatedText,
        ]
    );

    return rows[0];
};

export const fetchScopeForUser = async (userId, scopeId) => {
    const query = 'SELECT * FROM scopes WHERE id = $1 AND user_id = $2';
    const { rows } = await pool.query(query, [scopeId, userId]);
    return rows[0];
};
const scopeService = {

    createQuestionnaire,

    processScopeGeneration,

    fetchScopeForUser,

    generatePdfBuffer,

};

export default scopeService;