import { Readable } from "stream";
import cloudinary from "../config/cloudinary.js";
import PDFDocument from 'pdfkit';
import pool from '../config/database.js';
import { GoogleGenAI } from '@google/genai';

const ai = new GoogleGenAI({});

export const createQuestionnaire = async (userId, mcqAnswers, projectOverview) => {
    const query = `
        INSERT INTO questionnaires (user_id, mcq_answers, project_overview)
        VALUES ($1, $2, $3) RETURNING *;
    `;
    const values = [userId, JSON.stringify(mcqAnswers), projectOverview];
    const { rows } = await pool.query(query, values);
    return rows[0];
};


const callLLM = async (mcqAnswers, overview) => {
    try {
        
const prompt = `
You are a Senior Software Architect and Project Manager.

Based on the following project information, return ONLY valid JSON.

Project Overview:
${overview}

Questionnaire:
${JSON.stringify(mcqAnswers, null, 2)}

Return the response in this exact format:

{
  "executiveSummary": "",
  "deliverables": [
    ""
  ],
  "techStack": {
    "frontend": "",
    "backend": "",
    "database": ""
  },
  "timeline": "",
  "milestones": [
    ""
  ]
}

Rules:

1. Return ONLY JSON.
2. Do NOT use Markdown.
3. Do NOT use \`\`\`json.
4. Recommend the most suitable technology stack.
5. Keep the executive summary under 150 words.
6. Deliverables must be concise.
7. Milestones should be in chronological order.
`;

        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
        });

        // Return the clean text generated by the AI
let text = response.text.trim();

// Remove markdown if Gemini accidentally returns it
if (text.startsWith("```")) {
    text = text
        .replace(/^```json/i, "")
        .replace(/^```/, "")
        .replace(/```$/, "")
        .trim();
}

return JSON.parse(text);
    } catch (error) {
        console.error("Gemini AI Generation Error:", error);
        throw new Error("Failed to generate scope document via AI.");
    }
};

const generatePdfBuffer = (scope) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument();

    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));

    doc.on("end", () => {
      resolve(Buffer.concat(chunks));
    });

    doc.on("error", reject);

    // Title
    doc.fontSize(20)
      .text("PROJECT SCOPE DOCUMENT", {
        align: "center",
      });

    doc.moveDown();

    // Executive Summary
    doc.fontSize(16).text("Executive Summary");

    doc.fontSize(12).text(scope.executiveSummary);

    doc.moveDown();

    // Deliverables
    doc.fontSize(16).text("Deliverables");

    scope.deliverables.forEach(item => {
      doc.text("• " + item);
    });

    doc.moveDown();

    // Tech Stack
    doc.fontSize(16).text("Recommended Tech Stack");

    doc.text(`Frontend: ${scope.techStack.frontend}`);
    doc.text(`Backend: ${scope.techStack.backend}`);
    doc.text(`Database: ${scope.techStack.database}`);

    doc.moveDown();

    // Timeline
    doc.fontSize(16).text("Timeline");

    doc.text(scope.timeline);

    doc.moveDown();

    // Milestones
    doc.fontSize(16).text("Milestones");

    scope.milestones.forEach(item => {
      doc.text("• " + item);
    });

    doc.end();
  });
};
const uploadPdfToCloudinary = (pdfBuffer, fileName) => {

    return new Promise((resolve, reject) => {

        const uploadStream = cloudinary.uploader.upload_stream(

            {
                resource_type: "raw",
                folder: "scope-pdfs",
                public_id: fileName,
                overwrite: true,
            },

            (error, result) => {

                if (error) {

                    reject(error);

                } else {

                    resolve(result);

                }

            }

        );

        Readable.from(pdfBuffer).pipe(uploadStream);

    });

};


export const processScopeGeneration = async (userId, questionnaireId) => {

    // Verify questionnaire belongs to logged in user
    const qCheck = await pool.query(
        `
        SELECT *
        FROM questionnaires
        WHERE id = $1
        AND user_id = $2
        `,
        [questionnaireId, userId]
    );

    if (!qCheck.rows.length) {
        throw new Error("Questionnaire not found or access denied.");
    }

    const questionnaire = qCheck.rows[0];

    // Generate scope using Gemini
    const generatedScope = await callLLM(
        questionnaire.mcq_answers,
        questionnaire.project_overview
    );

    // ONLY return generated scope
    return generatedScope;
};

export const saveScope = async (
    userId,
    questionnaireId,
    generatedScope
) => {

    // Generate PDF

    const pdfBuffer = await generatePdfBuffer(generatedScope);

    // Upload PDF

    const cloudinaryResult = await uploadPdfToCloudinary(

        pdfBuffer,

        `scope_${userId}_${Date.now()}`

    );

    // Save in DB

    const insertQuery = `

        INSERT INTO scopes
        (
            user_id,
            questionnaire_id,
            scope_text,
            pdf_public_id,
            pdf_url
        )

        VALUES
        (
            $1,
            $2,
            $3,
            $4,
            $5
        )

        RETURNING *;

    `;

    const { rows } = await pool.query(

        insertQuery,

        [

            userId,

            questionnaireId,

            JSON.stringify(generatedScope),

            cloudinaryResult.public_id,

            cloudinaryResult.secure_url

        ]

    );

    rows[0].scope_text = JSON.parse(rows[0].scope_text);

    return rows[0];

};
export const fetchScopeForUser = async (userId, scopeId) => {

    const query =

        "SELECT * FROM scopes WHERE id=$1 AND user_id=$2";

    const { rows } = await pool.query(

        query,

        [scopeId, userId]

    );

    if (!rows.length) return null;

    rows[0].scope_text = JSON.parse(rows[0].scope_text);

    return rows[0];

};
const scopeService = {

    createQuestionnaire,

    processScopeGeneration,

    saveScope,

    fetchScopeForUser,

    generatePdfBuffer,

};

export default scopeService;